apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-enhanced-react-dashboard
  labels:
    app: ai-enhanced-react-dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai-enhanced-react-dashboard
  template:
    metadata:
      labels:
        app: ai-enhanced-react-dashboard
    spec:
      containers:
      - name: ai-enhanced-react-dashboard
        image: your_docker_username/ai-enhanced-react-dashboard:latest
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://mongo:27017/ai-enhanced-react-dashboard"
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ai-enhanced-react-dashboard
spec:
  selector:
    app: ai-enhanced-react-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
